management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    info:
      env:
        enabled: true
  info:
    app:
      name: MyNewApp
      description: App
      version: 1.0.0

spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://localhost:5432/ecomdb
    username: sara
    password: sara
  jpa:
    database: POSTGRESQL
    dhow-sql: true
    hibernate:
      ddl-auto: update
    database-platform:
      org.hibernate.dialect.PostreSQLDIALECT
#  h2:
#    console:
#      enabled: true
#    datasource:
#      url: jdbc:h2:mem:test
#    jpa:
#      show-sql: true
#      hibernate:
#        ddl-auto: create
